variable "management_group_id" {type = string}
variable "logAnalytics-CommonParameter" {type = string}
variable "diagnosticSettingName-CommonParameter" {type = string}
variable "categoryGroup-CommonParameter" {type = string}
variable "resourceLocationList-CommonParameter" {type = list }
variable "applicableResourceType-DeployDiagnosticsACI" {type = string}
variable "applicableResourceType-DeployDiagnosticsEventGridSub" {type = string}
variable "applicableResourceType-DeployDiagnosticsNIC" {type = string}
variable "applicableResourceType-DeployDiagnosticsSA" {type = string}
variable "applicableResourceType-DeployDiagnosticsSABlob" {type = string}
variable "applicableResourceType-DeployDiagnosticsSAFile" {type = string}
variable "applicableResourceType-DeployDiagnosticsSAQueue" {type = string}
variable "applicableResourceType-DeployDiagnosticsSATable" {type = string}
variable "applicableResourceType-DeployDiagnosticsVM" {type = string}
variable "applicableResourceType-DeployDiagnosticsVMSS" {type = string}
variable "applicableResourceType-DeployDiagnosticsWebServerFarm" {type = string}
variable "logsToCollect-DeployDiagnosticsACI" {type = list }
variable "logsToCollect-DeployDiagnosticsEventGridSub" {type = list }
variable "logsToCollect-DeployDiagnosticsNIC" {type = list }
variable "logsToCollect-DeployDiagnosticsSA" {type = list }
variable "logsToCollect-DeployDiagnosticsSAsubresource" {type = list }
variable "logsToCollect-DeployDiagnosticsVM" {type = list }
variable "logsToCollect-DeployDiagnosticsVMSS" {type = list }
variable "logsToCollect-DeployDiagnosticsWebServerFarm" {type = list }
variable "metricsToCollect-DeployDiagnosticsACI" {type = list }
variable "metricsToCollect-DeployDiagnosticsEventGridSub" {type = list }
variable "metricsToCollect-DeployDiagnosticsNIC" {type = list }
variable "metricsToCollect-DeployDiagnosticsSA" {type = list }
variable "metricsToCollect-DeployDiagnosticsVM" {type = list }
variable "metricsToCollect-DeployDiagnosticsVMSS" {type = list }
variable "metricsToCollect-DeployDiagnosticsWebServerFarm" {type = list }
variable "effect-DeployDiagnosticsAA" {type = string}
variable "effect-DeployDiagnosticsACApp" {type = string}
variable "effect-DeployDiagnosticsACI" {type = string}
variable "effect-DeployDiagnosticsACR" {type = string}
variable "effect-DeployDiagnosticsAnalysisService" {type = string}
variable "effect-DeployDiagnosticsAPIMgmt" {type = string}
variable "effect-DeployDiagnosticsApplicationGateway" {type = string}
variable "effect-DeployDiagnosticsCognitiveServices" {type = string}
variable "effect-DeployDiagnosticsCosmosDB" {type = string}
variable "effect-DeployDiagnosticsDatabricks" {type = string}
variable "effect-DeployDiagnosticsDataExplorerCluster" {type = string}
variable "effect-DeployDiagnosticsDataExplorerClusterSynaps" {type = string}
variable "effect-DeployDiagnosticsDataFactory" {type = string}
variable "effect-DeployDiagnosticsEventGridNamespace" {type = string}
variable "effect-DeployDiagnosticsEventGridSub" {type = string}
variable "effect-DeployDiagnosticsEventGridSystemTopic" {type = string}
variable "effect-DeployDiagnosticsEventGridTopic" {type = string}
variable "effect-DeployDiagnosticsFirewall" {type = string}
variable "effect-DeployDiagnosticsFrontDoor" {type = string}
variable "effect-DeployDiagnosticsFrontDoorCDN" {type = string}
variable "effect-DeployDiagnosticsGrafana" {type = string}
variable "effect-DeployDiagnosticsLoadBalancer" {type = string}
variable "effect-DeployDiagnosticsMySQL" {type = string}
variable "effect-DeployDiagnosticsMySQLFlexibleservers" {type = string}
variable "effect-DeployDiagnosticsNetworkSecurityGroups" {type = string}
variable "effect-DeployDiagnosticsNIC" {type = string}
variable "effect-DeployDiagnosticsNotificationHubs" {type = string}
variable "effect-DeployDiagnosticsNSG" {type = string}
variable "effect-DeployDiagnosticsPostgreSQL" {type = string}
variable "effect-DeployDiagnosticsPostgreSQLFlexibleservers" {type = string}
variable "effect-DeployDiagnosticsRedisCache" {type = string}
variable "effect-DeployDiagnosticsSA" {type = string}
variable "effect-DeployDiagnosticsSignalR" {type = string}
variable "effect-DeployDiagnosticsSQLMI" {type = string}
variable "effect-DeployDiagnosticsTrafficManager" {type = string}
variable "effect-DeployDiagnosticsVirtualNetwork" {type = string}
variable "effect-DeployDiagnosticsVM" {type = string}
variable "effect-DeployDiagnosticsVMSS" {type = string}
variable "effect-DeployDiagnosticsWebServerFarm" {type = string}
variable "effect-DeployDiagnosticsWebsiteFunction" {type = string}
